[versions]
androidx-core = "1.16.0"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
lifecycle-runtime-ktx = "2.8.7" # Updated stable version

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
